---
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.139.0
    container_name: otel-collector
    restart: unless-stopped
    user: "0:0"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=homelab,host.name=djan-pi
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    networks:
      - miniflux_default
    ports:
      # for traces from the synology NAS
      - "192.168.1.136:4317:4317"
      - "192.168.1.136:4318:4318"

networks:
  miniflux_default:
    external: true
