---
services:
  miniflux:
    image: miniflux/miniflux:2.3.3
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.miniflux.rule=Host(`miniflux.pi.djan.org`)
      - traefik.http.routers.miniflux.entrypoints=websecure
      - traefik.http.routers.miniflux.tls.certresolver=gandi
      - traefik.http.services.miniflux.loadbalancer.server.port=8080
    networks:
      - default
      - proxy
  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - underlab_miniflux_database:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=miniflux
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

networks:
  proxy:
    external: true

volumes:
  underlab_miniflux_database:
    external: true
