---
services:
  broker:
    image: docker.io/valkey/valkey:9-alpine
    restart: unless-stopped

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:3.0.3
    restart: unless-stopped
    depends_on:
      - broker
    volumes:
      - underlab_paperless_data:/usr/src/paperless/data
      - underlab_paperless_media:/usr/src/paperless/media
      - underlab_paperless_export:/usr/src/paperless/export
      - underlab_paperless_consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBENGINE=postgresql
      - PAPERLESS_DBHOST=postgres
      - PAPERLESS_DBPORT=5432
      - PAPERLESS_DBNAME=paperless
      - PAPERLESS_DBUSER=${POSTGRES_USER}
      - PAPERLESS_DBPASS=${POSTGRES_PASSWORD}
      - PAPERLESS_TIKA_ENABLED=0
      - PAPERLESS_TASK_WORKERS=1
      - PAPERLESS_THREADS_PER_WORKER=1
      - PAPERLESS_WEBSERVER_WORKERS=1
      - PAPERLESS_URL=https://paperless.pi.djan.org
      - PAPERLESS_CSRF_TRUSTED_ORIGINS=https://paperless.pi.djan.org
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.paperless.rule=Host(`paperless.pi.djan.org`)
      - traefik.http.routers.paperless.entrypoints=websecure
      - traefik.http.routers.paperless.tls.certresolver=gandi
      - traefik.http.services.paperless.loadbalancer.server.port=8000
    networks:
      - default
      - proxy

  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - underlab_paperless_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=paperless

networks:
  proxy:
    external: true

volumes:
  underlab_paperless_data:
    external: true
  underlab_paperless_media:
    external: true
  underlab_paperless_export:
    external: true
  underlab_paperless_consume:
    external: true
  underlab_paperless_database:
    external: true
