---
services:
  traefik:
    image: traefik:v3
    restart: unless-stopped
    command:
      - --log.level=INFO
      - --accesslog=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.gandi.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.gandi.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.gandi.acme.dnschallenge=true
      - --certificatesresolvers.gandi.acme.dnschallenge.provider=gandiv5
    environment:
      - GANDIV5_PERSONAL_ACCESS_TOKEN=${GANDIV5_PERSONAL_ACCESS_TOKEN}
      - TRAEFIK_AUTH=${TRAEFIK_AUTH}
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - underlab_traefik_letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.pi.djan.org`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=gandi
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH}
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  underlab_traefik_letsencrypt:
    external: true
